const GAME_CONFIG = {
  GAME_TIMER_INTERVAL: 1000,
  PLAYER_LIFE_COUNT: 3,
  ENEMY_TANKS_COUNT: 21,
  BULLET_STEP: 64,
  BULLET_SPEED_TIME: 100,
  UPDATES_TIMER: 1000,
  IS_GAME_OVER: false,
  PLAYER_PROPS: ['ENEMY_TANKS_COUNT', 'enemy', 'You'],
  ENEMY_PROPS: ['PLAYER_LIFE_COUNT', 'player', 'Enemies'],
};
export default GAME_CONFIG;
